### ISSUE TITLE
Remove .pdb files to save space in the archive?

### ISSUE THREAD

**Issue by traversaro** [robotology/robotology-superbuild-dependencies-vcpkg#33]
The dependency archive are relatively big (the archive with Gazebo is 4.9 giga once unzipped), and one reason is that the full .pdb (i.e. debug symbols, see https://stackoverflow.com/questions/3899573/what-is-a-pdb-file) are available for all the compiled dependencies.

Avoiding to ship .pdb files would probably save several gigas in the unzipped archive. As we seldom need to step in the libraries provided by vcpkg, I guess a possible idea is to drop the .pdb to have smaller archives that are easier to process. Ideally we could also provide a separate archive for just the .pdb files, but unless it is actually necessary I don't think the trouble is worth the effort in setting that up. 

Note that if we just remove the .pdb files is still possible to compile and run code in Debug mode, simply it will not be possible to step in the functions of the libraries provided by `vcpkg`. 

Related: https://github.com/iit-danieli-joint-lab/idjl-software-dependencies-vcpkg/issues/17 .

**Comment by traversaro** [comment]
cc @S-Dafarra

**Comment by S-Dafarra** [comment]
I think it is not a big deal for the dependencies. It would be like on Linux. If I am not wrong when downloading a dependency through ``apt``, those symbols are not available.

**Comment by traversaro** [comment]
> If I am not wrong when downloading a dependency through apt, those symbols are not available.

**Comment by traversaro** [comment]
Given the feedback, I guess we can go forward on this.
