### ISSUE TITLE
releases/download/v0.5.1/vcpkg-robotology-yarp-only.zip no longer available

### ISSUE THREAD

**Issue by drdanz** [robotology/robotology-superbuild-dependencies-vcpkg#41]
I'm not sure about what happened, but YARP continuous integration stopped working because this file is no longer available.

**Comment by drdanz** [comment]
Not sure if it is worth investigating, I'll just switch to v0.6.0

**Comment by traversaro** [comment]
v0.5.1 was a pre-release in which the upload jobs never completed even if I restarted it several times, given that it was incomplete I delete it, sorry I had no idea it was used somewhere.

**Comment by drdanz** [comment]
No problem, I used it in YARP, since the "yarp-only" package was not available in 0.5.
I'm closing this, thanks
